In [1]:
import numpy as np
import pandas as pd
from load_file import load_csv
from sklearn.metrics import mean_squared_error

In [2]:
signal = lambda number: 1 if number >= 0 else -1

In [3]:
test_adaline = lambda x, w: np.array([signal(w @ sample) for sample in x])

In [4]:
calc_mse = lambda x, d, w: sum([(d[i] - w @ x[i]) ** 2  for i in range(d.shape[0])])

In [145]:
def calc_mse(x, d, w):
  mse = 0
  p = d.shape[0]
  
  for i in range(p):
    u = w @ x[i]
    mse += (d[i] - u) ** 2
    
  return mse / p

In [5]:
def train_adaline(x, d, n=0.01, e=10**-3, w=[]):
  samples = d.shape[0]
  inputs = x.shape[1]
  epochs = 0
  
  if w == []:
    w = np.random.random([1, inputs])
  initial_w = np.copy(w)

  while True:
    epochs += 1
    
    last_mse = calc_mse(x, d, w)
    for i in range(samples):
      u = w @ x[i]
      w += n * (d[i] - u) * x[i]
    current_mse = calc_mse(x, d, w)
        
    if abs(current_mse - last_mse) <= e: break
      
  return initial_w, w, epochs

In [19]:
x, d = load_csv('../../datasets/valvula.csv')
df_d = pd.Series(d, name='d')
x

array([[-1.0000e+00,  4.3290e-01, -1.3719e+00,  7.0220e-01, -8.5350e-01],
       [-1.0000e+00,  3.0240e-01,  2.2860e-01,  8.6300e-01,  2.7909e+00],
       [-1.0000e+00,  1.3490e-01, -6.4450e-01,  1.0530e+00,  5.6870e-01],
       [-1.0000e+00,  3.3740e-01, -1.7163e+00,  3.6700e-01, -6.2830e-01],
       [-1.0000e+00,  1.1434e+00, -4.8500e-02,  6.6370e-01,  1.2606e+00],
       [-1.0000e+00,  1.3749e+00, -5.0710e-01,  4.4640e-01,  1.3009e+00],
       [-1.0000e+00,  7.2210e-01, -7.5870e-01,  7.6810e-01, -5.5920e-01],
       [-1.0000e+00,  4.4030e-01, -8.0720e-01,  5.1540e-01, -3.1290e-01],
       [-1.0000e+00, -5.2310e-01,  3.5480e-01,  2.5380e-01,  1.5776e+00],
       [-1.0000e+00,  3.2550e-01, -2.0000e+00,  7.1120e-01, -1.1209e+00],
       [-1.0000e+00,  5.8240e-01,  1.3915e+00, -2.2910e-01,  4.1735e+00],
       [-1.0000e+00,  1.3400e-01,  6.0810e-01,  4.4500e-01,  3.2230e+00],
       [-1.0000e+00,  1.4800e-01, -2.9880e-01,  4.7780e-01,  8.6490e-01],
       [-1.0000e+00,  7.3590e-01,  1.8

In [16]:
i_w, f_w, ep = train_adaline(x, d, e=10**-3)
print(i_w, f_w, ep)
test_adaline(x, f_w) == d

[[0.43568512 0.21746554 0.55448849 0.3705819 ]] [[-2.52973996  1.51101274  2.36731125 -0.65810815]] 324


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False])

In [68]:
for i in range(1, 6):
  initial_w, w, epochs = train_perceptron(x, d, n=.01)
  print('Training {} - {} epochs\nInitial weights: {}\nFinal weights: {}\n'.format(i, epochs, initial_w, w))

Training 1 - 418 epochs
Initial weights: [[0.24394912 0.06925139 0.54511994 0.36482102]]
Final weights: [[-3.11605088  1.57216539  2.49771594 -0.74240898]]

Training 2 - 455 epochs
Initial weights: [[0.80987081 0.93672274 0.469408   0.94248695]]
Final weights: [[-3.17012919  1.56648674  2.55856    -0.75697505]]

Training 3 - 434 epochs
Initial weights: [[0.92826204 0.72040465 0.12597186 0.23730693]]
Final weights: [[-3.09173796  1.56373665  2.49663186 -0.73612707]]

Training 4 - 400 epochs
Initial weights: [[0.3916246  0.04650943 0.44252502 0.79853097]]
Final weights: [[-3.0483754   1.54772343  2.46295902 -0.72888703]]

Training 5 - 433 epochs
Initial weights: [[0.2676866  0.63051339 0.65205756 0.3681343 ]]
Final weights: [[-3.1123134   1.57879939  2.50643956 -0.7415137 ]]



In [5]:
initial_weights = np.array([[0.24394912,0.06925139,0.54511994,0.36482102],
                            [0.80987081,0.93672274,0.469408,0.94248695],
                            [0.92826204,0.72040465,0.12597186,0.23730693],
                            [0.3916246,0.04650943,0.44252502,0.79853097],
                            [0.2676866,0.63051339,0.65205756,0.3681343]])

In [6]:
trained_weights = np.array([[-3.11605088,1.57216539,2.49771594,-0.74240898],
                           [-3.17012919,1.56648674,2.55856,-0.75697505],
                           [-3.09173796,1.56373665,2.49663186,-0.73612707],
                           [-3.0483754,1.54772343,2.46295902,-0.72888703],
                           [-3.1123134,1.57879939,2.50643956,-0.7415137]])

In [230]:
inputs = pd.read_csv('../../datasets/petroleo2.csv').to_numpy()
inputs

array([[-1.    , -0.3665,  0.062 ,  5.9891],
       [-1.    , -0.7842,  1.1267,  5.5912],
       [-1.    ,  0.3012,  0.5611,  5.8234],
       [-1.    ,  0.7757,  1.0648,  8.0677],
       [-1.    ,  0.157 ,  0.8028,  6.304 ],
       [-1.    , -0.7014,  1.0316,  3.6005],
       [-1.    ,  0.3748,  0.1536,  6.1537],
       [-1.    , -0.692 ,  0.9404,  4.4058],
       [-1.    , -1.397 ,  0.7141,  4.9263],
       [-1.    , -1.8842, -0.2805,  1.2548]])

In [229]:
results = pd.DataFrame(
  {'y' + str(i + 1):
   test_perceptron(inputs, trained_weights[i])
   for i in range(5)}
)
results

y1  y2  y3  y4  y5
0  -1  -1  -1  -1  -1
1   1   1   1   1   1
2   1   1   1   1   1
3   1   1   1   1   1
4   1   1   1   1   1
5   1   1   1   1   1
6  -1  -1  -1  -1  -1
7   1   1   1   1   1
8  -1  -1  -1  -1  -1
9  -1  -1  -1  -1  -1